### ISSUE TITLE
🐞[BUG] Blank screen after submitting TX

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/ui#123]
**Describe the bug**

A user reported that when submitting mining claims, the screen would go blank and have to be refreshed before used again.

It may also happen on the mining page, and all tx responses should be reviewed.

**Expected behavior**

The screen should display the tx information and allow for additional interaction.

**Additional Info**

This was reported from Google Chrome with Hiro Wallet 3.0.0.

**Comment by whoabuddy** [comment]
Found some console errors related to this today to help narrow it down, looks related to the [LinkTx component](https://github.com/citycoins/citycoin-ui/blob/main/src/components/common/LinkTx.js) or something possibly changed with how the `txId` is returned from the wallet.

```
TypeError: e.startsWith is not a function
    at ee (LinkTx.js:4:9)
    at ia (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at xu (react-dom.production.min.js:250:347)
    at Ou (react-dom.production.min.js:250:278)
    at ku (react-dom.production.min.js:250:138)
    at vu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Hi (react-dom.production.min.js:122:325)
ss @ react-dom.production.min.js:216

index.ts:118 [Connect] Error during transaction request TypeError: e.startsWith is not a function
    at ee (LinkTx.js:4:9)
    at ia (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at xu (react-dom.production.min.js:250:347)
    at Ou (react-dom.production.min.js:250:278)
    at ku (react-dom.production.min.js:250:138)
    at vu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Hi (react-dom.production.min.js:122:325)
(anonymous) @ index.ts:118
```

**Comment by whoabuddy** [comment]
Closing out - this was fixed by a release in the web wallet.
